project:
  type: website

website:
  title: "Jennifer Luz Lopes"
  site-url: "https://jenniluzlopes.github.io"
  reader-mode: true
  back-to-top-navigation: true

  navbar:
    left:
      - text: "Projetos"
        href: projetos/index.qmd
      - text: "Newsletter - CafÃ© com R"
        href: cafecomr/index.qmd
      - text: "ConteÃºdos|Ensino"
        href: apresentaÃ§Ãµes/index.qmd
    right:
      - text: "Agenda 2026"
        href: agenda_2026/index.qmd
      - text: "Sobre mim"
        href: about.qmd

  page-footer:
    center: |
      Site feito com ðŸ¤Ž e [Quarto](https://quarto.org/docs/websites/)  
      Â© 2025 Jennifer Luz Lopes

format:
  html:
    theme:
      light: litera
      dark: litera
    css:
      - css/estilo_geral.scss
    include-after-body:
      - text: |
          <!-- Script para navbar dinÃ¢mica -->
          <script src="scripts/navbar-scroll.js"></script>
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true

resources:
  - css/estilo_geral.scss
  - scripts/navbar-scroll.js
  - imagens/

editor: visual

